language: node_js
node_js:
- '0.10'
- '0.11'

notifications:
  email:
    on_success: always

before_install:
  # Turn off warnings about SSH keys:
  - echo "Host heroku.com" >> ~/.ssh/config
  - echo "   StrictHostKeyChecking no" >> ~/.ssh/config
  - echo "   CheckHostIP no" >> ~/.ssh/config
  - echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config

  # Install brunch and bower
  - npm install -g brunch
  - npm install -g bower

install: npm install & bower install
script: npm test

after_success:
  # check for pull request and correct python version
  - if [[ "$TRAVIS_PULL_REQUEST" == "true" ]]; then exit 0; fi
  - if [[ "$TRAVIS_NODE_VERSION" != "0.10" ]]; then exit 0; fi

  # Decrypt and add SSH key
  - openssl aes-256-cbc -d -k "$secret" -in id_rsa_travis.enc -a -out id_rsa_travis
  - ssh-add -D
  - chmod 600 id_rsa_travis
  - ssh-add ./id_rsa_travis

  # Get to the Travis build directory, configure git, and add remote repo
  - cd $HOME
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "travis-ci"
  - git remote add reubano git@github.com:reubano/reubano.github.com.git

  # Build optimized site, commit and push the Changes
  - brunch build -P
  - git checkout --orphan gh-pages
  - rm -r test
  - mv -f public/* ./
  - git add -f fonts images javascripts stylesheets index.html crossdomain.xml *.txt
  - git commit -m "Update site"
  - yes | git push reubano master

env:
  global:
    secure: MOg1NVJAmRusHc6dx0ksS/JGbjmmb+wfQlqsJbArBQg2mxhA952CXObUaNV8BcSnuiuxw4TrcRH+klrWZr3XsW/z+DJFeR6mQPK56jXCEKhIAOdRLoDG+hMfx0JuhDwphfM9A6C7kb0fLoEWJDbtr7FvDUcZA4h23HU2NEiua20=
