module.exports = (match) ->
  console.log 'start router'
  match '', 'page#index'
  match ':type', 'page#index'
  match ':type/page', 'page#index'
  match ':type/page/:num', 'page#index'
  match ':type/item', 'page#show'
  match ':type/item/:id', 'page#show'
  match ':type/archives', 'page#archives'
  match ':type/:year/:month/:day/:id', 'page#show'
